import type {
  DashboardMetric,
  Question,
  RouteCard,
  StudyMission,
  StudySession,
  Topic,
} from "./types";

import { countExamReadyTopics, countTouchedTopics } from "./topic-progress";

export const routeCards: RouteCard[] = [
  {
    href: "/dashboard",
    title: "Dashboard",
    description: "Morning mission, weekly hours, progress, and monitoring status.",
  },
  {
    href: "/topics",
    title: "Topics",
    description: "Live-capable Notion-backed topic checklist with explicit local fallback.",
  },
  {
    href: "/questions",
    title: "Questions",
    description: "Read-only question bank for past-exam practice, formulas, and legal review.",
  },
  {
    href: "/calendar",
    title: "Calendar",
    description: "Editable current-week planner built around the morning study schedule.",
  },
  {
    href: "/focus",
    title: "Focus",
    description: "Timer-driven focus session with review decisions and output tracking.",
  },
  {
    href: "/monitoring",
    title: "Monitoring",
    description: "Manual BOE/AEMET monitoring status until automation exists.",
  },
  {
    href: "/settings",
    title: "Settings",
    description: "Future profile, integrations, verification, and reminders setup.",
  },
];

export const studyMission: StudyMission = {
  mainTopic: "07:30-09:00 deep technical topic",
  practiceBlock: "09:10-10:10 questions or practical case",
  reviewBlock: "10:20-11:00 legal, informatics or flashcards",
  output: "Update confidence, log mistakes, and define the next review date.",
};

export const topics: Topic[] = [
  {
    id: "math-01",
    block: "Mathematics",
    officialNumber: "TODO_VERIFY_OFFICIAL_SOURCE",
    officialTitle: "TODO_VERIFY_OFFICIAL_SOURCE",
    normalizedTitle: "Calculus foundations",
    status: "in_progress",
    confidence: 2,
    priority: "high",
    nextReviewAt: "2026-06-21",
    verificationStatus: "unverified",
    sourceUrl: "TODO_VERIFY_OFFICIAL_SOURCE",
    retrievedAt: "TODO_VERIFY_OFFICIAL_SOURCE",
    shortDescription: "Limits, derivatives, and integration fundamentals.",
    studyFocus: "Rebuild confidence with core formulas and worked examples.",
    relatedQuestionCount: 0,
    notesStatus: "No notes yet",
  },
  {
    id: "met-01",
    block: "Meteorology and Climatology",
    officialNumber: "TODO_VERIFY_OFFICIAL_SOURCE",
    officialTitle: "TODO_VERIFY_OFFICIAL_SOURCE",
    normalizedTitle: "Atmospheric thermodynamics",
    status: "not_started",
    confidence: 1,
    priority: "high",
    nextReviewAt: "Pending schedule",
    verificationStatus: "needs_review",
    sourceUrl: "TODO_VERIFY_OFFICIAL_SOURCE",
    retrievedAt: "TODO_VERIFY_OFFICIAL_SOURCE",
    shortDescription: "Thermodynamic variables and parcel processes.",
    studyFocus: "Map the chapter before starting question practice.",
    relatedQuestionCount: 0,
    notesStatus: "No notes yet",
  },
  {
    id: "inf-01",
    block: "Informatics and Communications",
    officialNumber: "TODO_VERIFY_OFFICIAL_SOURCE",
    officialTitle: "TODO_VERIFY_OFFICIAL_SOURCE",
    normalizedTitle: "Computer networks and protocols",
    status: "reviewed",
    confidence: 4,
    priority: "medium",
    nextReviewAt: "2026-06-23",
    verificationStatus: "unverified",
    sourceUrl: "TODO_VERIFY_OFFICIAL_SOURCE",
    retrievedAt: "TODO_VERIFY_OFFICIAL_SOURCE",
    shortDescription: "Networking layers, addressing, and communication models.",
    studyFocus: "Keep protocol families and examples fresh.",
    relatedQuestionCount: 0,
    notesStatus: "Flashcards started",
  },
  {
    id: "gen-01",
    block: "General/Common",
    officialNumber: "TODO_VERIFY_OFFICIAL_SOURCE",
    officialTitle: "TODO_VERIFY_OFFICIAL_SOURCE",
    normalizedTitle: "Spanish public administration basics",
    status: "first_pass",
    confidence: 3,
    priority: "medium",
    nextReviewAt: "Next weekday review block",
    verificationStatus: "unverified",
    sourceUrl: "TODO_VERIFY_OFFICIAL_SOURCE",
    retrievedAt: "TODO_VERIFY_OFFICIAL_SOURCE",
    shortDescription: "State structure and public-sector fundamentals.",
    studyFocus: "Link constitutional structure to common exam prompts.",
    relatedQuestionCount: 0,
    notesStatus: "Outline complete",
  },
];

export const questions: Question[] = [
  {
    id: "q-met-thermo-01",
    name: "Atmospheric stability basics",
    type: "multiple_choice",
    sourceYear: 2024,
    sourceExam: "Mock AEMET A1 set",
    sourceUrl: "TODO_VERIFY_OFFICIAL_SOURCE",
    retrievedAt: "TODO_VERIFY_OFFICIAL_SOURCE",
    verificationStatus: "unverified",
    questionNumber: "1",
    statement:
      "Which process most directly increases the relative humidity of an unsaturated air parcel if water vapor content stays constant?",
    options: [
      "Increasing parcel temperature",
      "Decreasing parcel temperature",
      "Increasing pressure altitude definition only",
      "Reducing cloud condensation nuclei",
    ],
    correctAnswer: "Decreasing parcel temperature",
    answerSourceStatus: "inferred",
    explanation:
      "Cooling an unsaturated parcel raises relative humidity when vapor content does not change.",
    topicIds: ["met-01"],
    difficulty: 2,
    attemptsCount: 3,
    lastAttemptAt: "2026-06-20",
    nextReviewAt: "2026-06-21",
    mistakeTypes: ["concept"],
  },
  {
    id: "q-math-calc-01",
    name: "Gradient and extrema review",
    type: "formula",
    sourceYear: 2023,
    sourceExam: "Mock AEMET A1 set",
    sourceUrl: "TODO_VERIFY_OFFICIAL_SOURCE",
    retrievedAt: "TODO_VERIFY_OFFICIAL_SOURCE",
    verificationStatus: "needs_review",
    questionNumber: "7",
    statement:
      "For a differentiable function, what condition must hold at an interior local maximum point?",
    options: [
      "The derivative must be zero if it exists",
      "The second derivative must always be positive",
      "The function must be discontinuous nearby",
      "The gradient must increase without bound",
    ],
    correctAnswer: "The derivative must be zero if it exists",
    answerSourceStatus: "inferred",
    explanation:
      "At an interior local maximum, the first derivative vanishes when the derivative exists.",
    topicIds: ["math-01"],
    difficulty: 3,
    attemptsCount: 5,
    lastAttemptAt: "2026-06-18",
    nextReviewAt: "2026-06-19",
    mistakeTypes: ["formula", "time_management"],
  },
  {
    id: "q-gen-admin-01",
    name: "Public administration fundamentals",
    type: "legal_short_answer",
    sourceYear: 2022,
    sourceExam: "Mock AEMET A1 set",
    sourceUrl: "TODO_VERIFY_OFFICIAL_SOURCE",
    retrievedAt: "TODO_VERIFY_OFFICIAL_SOURCE",
    verificationStatus: "unverified",
    questionNumber: "12",
    statement:
      "Name one constitutional principle that constrains public administration action and explain it briefly.",
    options: [],
    correctAnswer: "TODO_VERIFY_OFFICIAL_SOURCE",
    answerSourceStatus: "unknown",
    explanation:
      "Short-answer review item used to rehearse legal wording before verified sources are imported.",
    topicIds: ["gen-01"],
    difficulty: 4,
    attemptsCount: 1,
    lastAttemptAt: "2026-06-21",
    nextReviewAt: "2026-06-25",
    mistakeTypes: ["legal_wording"],
  },
  {
    id: "q-inf-networks-01",
    name: "TCP/IP protocol stack quick check",
    type: "flashcard",
    sourceYear: 2024,
    sourceExam: "Mock AEMET A1 set",
    sourceUrl: "TODO_VERIFY_OFFICIAL_SOURCE",
    retrievedAt: "TODO_VERIFY_OFFICIAL_SOURCE",
    verificationStatus: "unverified",
    questionNumber: "19",
    statement: "Which transport protocol is connection-oriented: TCP or UDP?",
    options: ["TCP", "UDP"],
    correctAnswer: "TCP",
    answerSourceStatus: "inferred",
    explanation: "TCP is connection-oriented and adds reliability guarantees.",
    topicIds: ["inf-01"],
    difficulty: 1,
    attemptsCount: 2,
    lastAttemptAt: "2026-06-22",
    nextReviewAt: "2026-06-27",
    mistakeTypes: ["none"],
  },
];

export const studySessions: StudySession[] = [
  {
    id: "session-2026-06-22-deep-topic",
    name: "Thermodynamics deep block",
    sessionType: "deep_topic",
    objective: "Review parcel stability and rebuild the lapse-rate summary notes.",
    topicIds: ["met-01"],
    questionIds: ["q-met-thermo-01"],
    plannedDate: "2026-06-22",
    plannedStartTime: "07:30",
    plannedEndTime: "09:00",
    plannedDurationMinutes: 90,
    status: "completed",
    timerStatus: "finished",
    completed: true,
    reviewState: "done",
    notesCreated: true,
    questionsSolved: 1,
    flashcardsCreated: 2,
    mistakesLogged: 0,
    confidenceAfter: 3,
    nextReviewAt: "2026-06-24",
    notes: "Captured the dry and moist adiabatic comparison in study notes.",
    isTemplate: false,
    isPersisted: false,
  },
  {
    id: "session-2026-06-23-questions",
    name: "Calculus question block",
    sessionType: "questions",
    objective: "Solve derivative and extrema questions without skipping the setup steps.",
    topicIds: ["math-01"],
    questionIds: ["q-math-calc-01"],
    plannedDate: "2026-06-23",
    plannedStartTime: "09:10",
    plannedEndTime: "10:10",
    plannedDurationMinutes: 60,
    status: "ready_for_review",
    timerStatus: "finished",
    completed: false,
    reviewState: "waiting",
    notesCreated: false,
    questionsSolved: 4,
    flashcardsCreated: 0,
    mistakesLogged: 1,
    confidenceAfter: null,
    nextReviewAt: "",
    notes: "",
    isTemplate: false,
    isPersisted: false,
  },
  {
    id: "session-2026-06-24-legal",
    name: "Administration review block",
    sessionType: "legal",
    objective: "Summarize one constitutional principle with clean exam wording.",
    topicIds: ["gen-01"],
    questionIds: ["q-gen-admin-01"],
    plannedDate: "2026-06-24",
    plannedStartTime: "10:20",
    plannedEndTime: "11:00",
    plannedDurationMinutes: 40,
    status: "scheduled",
    timerStatus: "idle",
    completed: false,
    reviewState: "not_needed",
    notesCreated: false,
    questionsSolved: 0,
    flashcardsCreated: 0,
    mistakesLogged: 0,
    confidenceAfter: null,
    nextReviewAt: "",
    notes: "",
    isTemplate: false,
    isPersisted: false,
  },
];

export function buildDashboardMetrics(): DashboardMetric[] {
  return [
    {
      label: "Weekly study target",
      value: "8.5 h",
      detail: "Mock target based on three morning blocks across five weekdays.",
    },
    {
      label: "Topics touched",
      value: `${countTouchedTopics(topics)} / ${topics.length}`,
      detail: "Mock progress only. Exact syllabus wording is TODO_VERIFY_OFFICIAL_SOURCE.",
    },
    {
      label: "Exam-ready topics",
      value: `${countExamReadyTopics(topics)}`,
      detail: "Read-only Phase 1 data derived from the shared topic checklist.",
    },
    {
      label: "Monitoring",
      value: "Manual only",
      detail: "Automation is not implemented yet.",
    },
  ];
}
